'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Jsons
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Character_Editor__RuleSet5EPlugin_.Jsons", GetType(Jsons).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a {
        '''  &quot;reach&quot;: 5,
        '''  &quot;attacks&quot;: [],
        '''  &quot;attacksDC&quot;: [],
        '''  &quot;saves&quot;: [
        '''    {
        '''      &quot;name&quot;: &quot;STR&quot;,
        '''      &quot;type&quot;: &quot;Public&quot;,
        '''      &quot;roll&quot;: &quot;1D20+0&quot;
        '''    },
        '''    {
        '''      &quot;name&quot;: &quot;DEX&quot;,
        '''      &quot;type&quot;: &quot;Public&quot;,
        '''      &quot;roll&quot;: &quot;1D20+0&quot;
        '''    },
        '''    {
        '''      &quot;name&quot;: &quot;CON&quot;,
        '''      &quot;type&quot;: &quot;Public&quot;,
        '''      &quot;roll&quot;: &quot;1D20+0&quot;
        '''    },
        '''    {
        '''      &quot;name&quot;: &quot;INT&quot;,
        '''      &quot;type&quot;: &quot;Public&quot;,
        '''      &quot;roll&quot;: &quot;1D20+0&quot;
        '''    },
        '''    {
        '''      &quot;name&quot;: &quot;WIS&quot;,
        '''      &quot;type&quot;: &quot;Public&quot;,
        '''      &quot;roll&quot;: &quot;1D20+0&quot;
        '''    },
        '''    {
        '''      [resto de la cadena truncado]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property ___BaseHeroe() As String
            Get
                Return ResourceManager.GetString("___BaseHeroe", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
